export const controls:Record<string,string>={
'Steering wheel':'Changes the direction of the front wheels. Look ahead and use small, smooth movements.',
'Clutch':'In a manual car, disconnects engine power while you change gear. Your instructor will help you find the biting point.',
'Brake':'Reduces your speed and brings the vehicle to a controlled stop. Apply pressure smoothly.',
'Accelerator':'Controls engine power. Gentle pressure helps you build speed smoothly.',
'Gear lever':'Selects a gear suited to the situation. Gear patterns and reverse locks vary between vehicles.',
'Handbrake':'Keeps the vehicle secure while parked. It may be a lever or an electronic switch.',
'Rear-view mirror':'Helps you see traffic behind you. Adjust it while stationary before you set off.',
'Side mirrors':'Help you see beside and behind the car. They do not show every blind spot.',
'Indicators':'Tell other road users what you intend to do. A signal does not give you priority.',
'Dashboard':'Shows speed, fuel and vehicle warnings. Learn the warning lights in your vehicle handbook.',
'Seat belt':'Secures you in the seat. Fasten it and check your passengers before moving.'};
export const startingSteps=[['Seat position','Adjust your seat so you can comfortably reach the pedals and steering wheel.','Steering wheel'],['Seat belt','Fasten your belt and check that passengers are secured.','Seat belt'],['Mirrors','Adjust the mirrors for a clear view behind and beside you.','Rear-view mirror'],['Neutral gear','For this manual-car example, check neutral and keep the parking brake engaged. Follow your vehicle’s starting procedure.','Gear lever'],['Start engine','Follow the handbook. Some cars require the clutch or brake to be pressed before starting.','Dashboard'],['Check surroundings','Check mirrors, blind spots and the area around the car. Wait if it is not safe.','Side mirrors'],['Prepare to move','With your instructor, select the appropriate gear and release the parking brake only when ready to move safely.','Handbrake']];
export const gearCopy:Record<string,string>={'N':'Neutral disconnects drive through the gearbox. It is not a gear for coasting.','1':'First gear is used to begin moving and at very low speeds.','2':'Second gear supports low-speed progress once the car is moving.','3':'Third gear is often suitable for building speed when conditions allow.','4':'Fourth gear supports steady progress at a suitable road speed.','5':'Fifth gear is used for efficient cruising when the vehicle and conditions allow.','R':'Reverse is for moving backwards slowly. Stop fully before selecting it and check all around.'};
export const milestones=[
{title:'Know your car',tag:'THE FOUNDATIONS',mode:'cockpit',description:'Turn unfamiliar controls into familiar tools. Start in the driver’s seat.',tips:['Adjust your seat and mirrors while parked.','Identify each control before starting.','Read the handbook for your vehicle.']},
{title:'Start the vehicle',tag:'BEFORE YOU MOVE',mode:'cockpit',description:'A calm routine makes a confident beginning. Make your checks a habit.',tips:['Seat, belt and mirrors first.','Follow your vehicle’s starting procedure.','Check all around before moving.']},
{title:'Clutch control',tag:'FIND YOUR BALANCE',mode:'pedals',description:'Learn how gentle inputs work together to create a smooth start.',tips:['Practise in a safe area with an instructor.','Find the biting point gradually.','Pause and reset if the engine stalls.']},
{title:'Gear changes',tag:'KEEP IT SMOOTH',mode:'gear',description:'Choose a gear that suits the car, the road and the conditions.',tips:['Learn the pattern with the engine off.','Look at the road when changing gear.','Avoid fixed speed rules: cars differ.']},
{title:'Steering',tag:'LOOK WHERE YOU WANT TO GO',mode:'road',description:'Look ahead, follow a smooth path, and let small corrections do the work.',tips:['Keep a comfortable, controlled grip.','Look through the bend.','Avoid abrupt corrections.']},
{title:'Braking',tag:'SPACE TO SLOW DOWN',mode:'road',description:'Read the road early and create enough room for a calm, controlled stop.',tips:['Check mirrors before slowing when possible.','Apply the brake progressively.','Leave more space in poor conditions.']},
{title:'Turns & junctions',tag:'OBSERVE. THEN ACT.',mode:'city',description:'Mirror. Signal. Position. Speed. Observation. Give every junction your attention.',tips:['Look for pedestrians and cyclists.','Choose a suitable position and speed.','Enter only when your path is clear.']},
{title:'Reverse',tag:'SLOW IS A SKILL',mode:'parking',description:'Move slowly and keep checking around the whole vehicle.',tips:['Check blind spots before moving.','Use direct observation as well as mirrors.','Stop if you lose sight of a hazard.']},
{title:'Parking',tag:'MAKE ROOM FOR CONFIDENCE',mode:'parking',description:'Break the manoeuvre into small steps. Accuracy comes with patient practice.',tips:['Choose a safe, suitable space.','Reference points vary by vehicle.','Pause, observe and adjust as needed.']},
{title:'City driving',tag:'SHARE THE ROAD',mode:'city',description:'Build awareness of the people and vehicles sharing your space.',tips:['Stay within your lane.','Allow space for vulnerable road users.','Plan early for lights and crossings.']},
{title:'Highway driving',tag:'A WIDER HORIZON',mode:'highway',description:'Look further ahead and manage speed, space and lane changes with care.',tips:['Join only when permitted and safe.','Check mirrors and blind spots before changing lane.','Leave a safe gap and plan your exit early.']},
{title:'Driving test',tag:'BRING IT ALL TOGETHER',mode:'road',description:'Prepare with your instructor and practise the knowledge behind your decisions.',tips:['Check official local test requirements.','Review the skills you find difficult.','Use the practice test to spot knowledge gaps.']},
{title:'Independent driving',tag:'YOUR ROAD AHEAD',mode:'highway',description:'Keep learning long after the test. Confidence grows with responsible experience.',tips:['Start with familiar routes and conditions.','Avoid distractions and driving while tired.','Build up to challenging journeys gradually.']}
];
export const parkingSteps:Record<string,string[]>={
'Parallel parking':['Choose a suitable space and check all around.','Align safely beside the parked vehicle.','Reverse slowly while steering into the space.','Continue checking all around as you straighten.','Adjust your position and secure the car.'],
'Reverse parking':['Choose a suitable bay and check for people.','Position for a controlled approach.','Reverse slowly while observing all around.','Straighten within the bay and secure the car.'],
'Bay parking':['Choose a clear bay and plan your approach.','Approach slowly, checking nearby vehicles and people.','Steer smoothly into the bay.','Straighten and leave room to open the doors.'],
'Turning exercise':['Choose a safe, legal place with good visibility.','Check in every direction before each movement.','Move slowly and stop before changing direction.','Recheck the road before completing the turn.']};
export const questions=[
{q:'Before moving off, what should you check?',a:['Only the road ahead','Mirrors, blind spots and surroundings','Only the dashboard'],correct:1,why:'Mirrors alone cannot show every hazard. Check blind spots and the space around your car.'},
{q:'What is the clutch used for in a manual car?',a:['Disconnecting engine power while changing gear','Increasing grip on wet roads','Securing the parked car'],correct:0,why:'The clutch lets you disconnect engine power to change gears.'},
{q:'A green traffic light means…',a:['Go immediately','You have priority over everyone','Proceed only when safe and permitted'],correct:2,why:'Check that your path is clear and watch for pedestrians and other road users.'},
{q:'When should you select reverse?',a:['While still rolling forward','After stopping fully and checking around','Whenever a parking space appears'],correct:1,why:'Stop before selecting reverse and check all around before moving backwards.'},
{q:'In rain, you should…',a:['Leave more space and adapt your speed','Follow closer to see the car ahead','Keep the same gap in all conditions'],correct:0,why:'Rain can reduce visibility and grip. Give yourself more room to stop.'},
{q:'Which approach helps with smooth steering?',a:['Looking directly at the bonnet','Making sudden corrections','Looking ahead and making controlled inputs'],correct:2,why:'Looking ahead helps you anticipate the road and steer smoothly.'},
{q:'Does using an indicator give you priority?',a:['Always','No. You must still make sure it is safe','Only when changing lanes'],correct:1,why:'Signals communicate intention. They do not make other road users give way.'},
{q:'Are gear-change speed ranges universal?',a:['Yes, all cars use the same ranges','Only first gear is universal','No, the vehicle and conditions matter'],correct:2,why:'Engine characteristics, gradients and road conditions affect gear choice.'},
{q:'While reversing, a person enters your path. What should you do?',a:['Stop and wait until it is safe','Continue if your mirrors look clear','Use the horn and keep moving'],correct:0,why:'Stop whenever your path is unsafe or your view is uncertain.'},
{q:'What is the best next step after passing your test?',a:['Drive in every difficult condition straight away','Build experience gradually and keep good habits','Stop reviewing your driving'],correct:1,why:'Passing is a milestone. Continue learning and build experience at a sensible pace.'}
];
