"use client";
import { useEffect, useRef, useState } from "react";
import type * as THREE from "three";

type SceneProps={mode?:string;selected?:string;onSelect?:(value:string)=>void;progress?:number;weather?:string;className?:string;playing?:boolean};
function SceneEngine({mode="hero",selected="",onSelect,progress=0,weather="day",className="",playing=true}:SceneProps){
 const live=useRef({progress,playing});live.current={progress,playing};const [motion,setMotion]=useState(true);const motionRef=useRef(motion);motionRef.current=motion;const host=useRef<HTMLDivElement>(null);const callback=useRef(onSelect);callback.current=onSelect;
 const [error,setError]=useState(false);const [ready,setReady]=useState(false);
 useEffect(()=>{let cleanup=()=>{};let cancelled=false;const el=host.current;if(!el)return;
 const observer=new IntersectionObserver(async entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();
 try{const T=await import("three");const {RoundedBoxGeometry}=await import("three/addons/geometries/RoundedBoxGeometry.js");const {RoomEnvironment}=await import("three/addons/environments/RoomEnvironment.js");if(cancelled)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const touch=matchMedia('(pointer: coarse)').matches;
 const renderer=new T.WebGLRenderer({alpha:true,antialias:!touch,powerPreference:"low-power"});renderer.setPixelRatio(Math.min(devicePixelRatio,touch?1.3:1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=weather==='night'?.35:.85;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');cleanup=()=>{renderer.dispose();renderer.domElement.remove();};
 const scene=new T.Scene();const camera=new T.PerspectiveCamera(34,1,.1,150);const pmrem=new T.PMREMGenerator(renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.05);scene.environment=env.texture;scene.environmentIntensity=.55;room.dispose();pmrem.dispose();
 const ambient=new T.HemisphereLight(0xdce8cf,0x323d30,.8);scene.add(ambient);const sun=new T.DirectionalLight(0xf8ffe9,2.2);sun.position.set(-4,10,7);sun.castShadow=true;sun.shadow.mapSize.set(touch?512:1024,touch?512:1024);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;sun.shadow.normalBias=.03;scene.add(sun);const rim=new T.DirectionalLight(0xd3fa69,1);rim.position.set(6,3,-5);scene.add(rim);if(weather==='night'){ambient.intensity=.16;sun.intensity=.35;rim.intensity=.8;}if(weather==='rain'){scene.fog=new T.FogExp2('#263329',.017);const rainGeometry=new T.BufferGeometry();const positions=[];for(let i=0;i<140;i++){const x=Math.sin(i*127.1)*12,y=1+(i%19)*.3,z=Math.cos(i*311.7)*13;positions.push(x,y,z,x-.035,y-.23,z)}rainGeometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));scene.add(new T.LineSegments(rainGeometry,new T.LineBasicMaterial({color:'#93a999',transparent:true,opacity:.24})));}
 const mat=(color:string,metalness=0,roughness=.5)=>new T.MeshStandardMaterial({color,metalness,roughness});const paint=mat('#bccb92',.73,.22);const black=mat('#151a18',.25,.35);const rubber=mat('#0e1010',0,.88);const glass=mat('#1b2929',.75,.12);const chrome=mat('#bbc3b9',.95,.2);const white=mat('#eceede',.1,.65);const lime=mat('#d3fa69',.25,.3);const asphalt=mat(weather==='rain'?'#16221c':'#171e18',.1,weather==='rain'?.16:.85);
 const picks:THREE.Object3D[]=[];
 function mesh(g:THREE.BufferGeometry,m:THREE.Material,parent:THREE.Object3D=scene,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 function box(parent:THREE.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,m:THREE.Material,r=.03){return mesh(new RoundedBoxGeometry(w,h,d,2,r),m,parent,x,y,z)}
 function cyl(parent:THREE.Object3D,r:number,h:number,x:number,y:number,z:number,m:THREE.Material){return mesh(new T.CylinderGeometry(r,r,h,32),m,parent,x,y,z)}
 function label(parent:THREE.Object3D,text:string,x:number,y:number,z:number,w=1,h=.45,bg='#e9eddd',fg='#243022'){const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,512,256);ctx.fillStyle=fg;ctx.font='bold 180px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,135,470);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}),parent,x,y,z)}
 function interactive(obj:THREE.Object3D,name:string){obj.userData.control=name;obj.traverse(o=>{if(o instanceof T.Mesh){o.userData.control=name;picks.push(o);if(selected===name)o.material=lime}})}
 function car(parent:THREE.Object3D,color=paint){const c=new T.Group();parent.add(c);

// Sculpted body with continuous shoulder line, wheel arches, glazing and trim.
 const shape=new T.Shape();shape.moveTo(-2.03,.56);shape.quadraticCurveTo(-2.13,.9,-2.01,1.35);shape.lineTo(-1.69,1.94);shape.quadraticCurveTo(-1.6,2.02,-1.38,2.03);shape.lineTo(.55,2.03);shape.quadraticCurveTo(.76,2.02,.92,1.83);shape.lineTo(1.38,1.3);shape.quadraticCurveTo(1.86,1.27,2.08,1.14);shape.quadraticCurveTo(2.2,.94,2.13,.61);shape.lineTo(-2.03,.56);
 const body=mesh(new T.ExtrudeGeometry(shape,{depth:1.66,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.09,bevelThickness:.08}),color,c);body.rotation.y=-Math.PI/2;body.position.x=.83;
 // Front windshield and rear glazing.
 const windGeometry=new T.BufferGeometry();windGeometry.setAttribute('position',new T.Float32BufferAttribute([-.76,2.06,.65,.76,2.06,.65,.81,1.38,1.42,-.81,1.38,1.42],3));windGeometry.setIndex([0,2,1,0,3,2]);windGeometry.computeVertexNormals();const windshieldMaterial=new T.MeshPhysicalMaterial({color:'#273b36',metalness:.38,roughness:.12,clearcoat:1,side:T.DoubleSide});mesh(windGeometry,windshieldMaterial,c);box(c,.022,.018,.52,-.3,1.4,1.47,black).rotation.y=.35;
 const rear=box(c,1.45,.025,.73,0,1.74,-1.9,glass,.01);rear.rotation.x=-1.06;
 for(const side of [-1,1]){
 const windowShape=new T.Shape();windowShape.moveTo(-1.82,1.36);windowShape.lineTo(-1.54,1.91);windowShape.lineTo(.53,1.91);windowShape.lineTo(1.12,1.36);windowShape.closePath();const win=mesh(new T.ShapeGeometry(windowShape),glass,c,side*.931,0,0);win.rotation.y=-Math.PI/2;win.material=new T.MeshStandardMaterial({color:'#1a2625',metalness:.8,roughness:.14,side:T.DoubleSide});
 box(c,.036,.61,.075,side*.95,1.6,.16,black);box(c,.02,.035,2.25,side*.95,1.27,.12,chrome);box(c,.045,.025,.26,side*.977,1.2,-.37,chrome);box(c,.045,.025,.25,side*.977,1.2,.66,chrome);
 box(c,.31,.16,.28,side*1.075,1.39,.83,color,.06);box(c,.012,.11,.21,side*1.23,1.4,.83,glass);box(c,.07,.15,2.6,side*.94,.56,0,black);
 for(const z of [-1.42,1.46]){const arch=mesh(new T.TorusGeometry(.46,.065,8,40,Math.PI),black,c,side*.96,.51,z);arch.rotation.set(0,side*Math.PI/2,0);
 const wheel=new T.Group();wheel.position.set(side*.98,.48,z);wheel.rotation.z=Math.PI/2;c.add(wheel);cyl(wheel,.435,.25,0,0,0,rubber);cyl(wheel,.325,.27,0,0,0,chrome);cyl(wheel,.275,.285,0,0,0,black);for(let i=0;i<10;i++){const spoke=box(wheel,.042,.29,.25,Math.sin(i*Math.PI/5)*.14,0,Math.cos(i*Math.PI/5)*.14,chrome,.01);spoke.rotation.y=i*Math.PI/5}cyl(wheel,.083,.3,0,0,0,chrome);}
 }
 box(c,1.8,.22,.12,0,.65,2.24,black);box(c,1.14,.38,.055,0,.96,2.29,black);for(let i=0;i<5;i++)box(c,1.05,.015,.02,0,.77+i*.045,2.335,chrome,.005);
 const lamps=new T.MeshStandardMaterial({color:'#ffffe2',emissive:'#e8ffc4',emissiveIntensity:3});for(const side of [-1,1]){box(c,.48,.11,.12,side*.65,1.19,2.255,lamps);box(c,.42,.11,.08,side*.77,1.32,-2.04,mat('#e15843'));}label(c,'MH 01 TL 2026',0,.655,2.325,.68,.16);box(c,.55,.34,.16,0,2.18,0,white);label(c,'L',0,2.18,.087,.24,.28,'#f6f3df','#db4331');box(c,1.35,.03,.18,0,2.01,-.6,black);for(const side of [-1,1]){box(c,.018,.012,.53,side*.64,1.265,1.81,black,.003);const seam=box(c,.012,.5,.009,side*.983,.97,.16,black,.003);box(c,.012,.012,1.65,side*.988,.75,-.03,black,.002);}label(c,'L',0,2.18,-.088,.24,.28,'#f6f3df','#db4331').rotation.y=Math.PI;c.scale.set(1.02,.96,1.04);return c;}
 function cone(x:number,z:number){box(scene,.44,.07,.44,x,.055,z,black);mesh(new T.ConeGeometry(.17,.57,20),mat('#e89046'),scene,x,.36,z);cyl(scene,.11,.085,x,.36,z,white)}
 function road(){if(mode==='road'){const geometry=new T.BufferGeometry();const vertices=[],indices=[];for(let i=0;i<=80;i++){const z=-20+i*.5,center=Math.sin(z*.12)*1.6;vertices.push(center-4.8,-.055,z,center+4.8,-.055,z);if(i<80)indices.push(i*2,i*2+1,i*2+2,i*2+1,i*2+3,i*2+2)}geometry.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();mesh(geometry,asphalt);for(let z=-19;z<20;z+=2.5){const center=Math.sin(z*.12)*1.6;const dash=box(scene,.08,.014,1.1,center,-.035,z,white,.001);dash.rotation.y=Math.cos(z*.12)*.19;}for(const side of [-1,1]){const points=[];for(let i=0;i<=80;i++){const z=-20+i*.5;points.push(new T.Vector3(Math.sin(z*.12)*1.6+side*4.5,-.035,z))}mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points),80,.025,4,false),white)}return;}box(scene,10,.18,40,0,-.15,0,asphalt,.04);for(const x of [-4.55,4.55])box(scene,.06,.015,40,x,-.04,0,white,.001);for(let z=-19;z<21;z+=3)box(scene,.1,.015,1.4,0,-.04,z,white,.001);}
 function traffic(x:number,z:number){cyl(scene,.065,3,x,1.5,z,black);box(scene,.46,1.2,.3,x,3,z,black);['#f26757','#f7bd55','#badd71'].forEach((col,i)=>{const light=mesh(new T.SphereGeometry(.13,20,12),new T.MeshStandardMaterial({color:col,emissive:col,emissiveIntensity:(selected||'Red')===['Red','Amber','Green'][i]?2:.03}),scene,x,3.37-i*.35,z+.16);interactive(light,['Red','Amber','Green'][i]);});}
 function city(){for(let i=0;i<14;i++){const x=(i%2===0?-1:1)*(7+(i%3)*2);const z=-15+i*2;const h=2+(i*7%5);box(scene,2.3,h,2.4,x,h/2-.2,z,mat(i%2?'#394237':'#485043'),.04);for(let y=1;y<h;y+=.85)box(scene,.025,.4,1.6,x+(x<0?1.17:-1.17),y,z,mat('#869775',.2,.4));}}
 let roadGroup:THREE.Group|undefined;let vehicle:THREE.Group|undefined;let pedalObjects:THREE.Object3D[]=[];let wheel:THREE.Group|undefined;
 const baseCamera=new T.Vector3();const target=new T.Vector3();
 if(['cockpit','pedals','gear'].includes(mode)){
 scene.add(new T.AmbientLight(0xffffff,1));box(scene,4,.2,3.8,0,-.1,0,black);box(scene,3.8,.62,.75,0,1.22,-.95,black,.12);box(scene,3.6,.09,1,0,1.56,-1.15,mat('#343c34'),.05);box(scene,1,.48,.12,.9,1.42,-.52,mat('#090e0c'),.1);
 for(const x of [.7,1.15]){const d=mesh(new T.TorusGeometry(.16,.012,8,40),chrome,scene,x,1.45,-.438);label(scene,'0',x,1.45,-.42,.19,.13,'#101a13','#d3fa69');}
 wheel=new T.Group();wheel.position.set(.9,1.3,.03);wheel.rotation.x=-.2;scene.add(wheel);mesh(new T.TorusGeometry(.44,.055,12,48),black,wheel);mesh(new T.TorusGeometry(.444,.01,8,48),chrome,wheel,0,0,-.015);box(wheel,.18,.2,.14,0,0,0,black);for(const a of [0,2.1,4.2]){const spoke=box(wheel,.065,.38,.05,Math.sin(a)*.18,Math.cos(a)*.18,0,chrome);spoke.rotation.z=-a;}interactive(wheel,'Steering wheel');
 for(let i=0;i<3;i++){const p=new T.Group();p.position.set(.48+i*.42,.29,-.12);p.rotation.x=-.3;scene.add(p);box(p,.045,.43,.055,0,.15,-.04,chrome);box(p,i===2?.15:.24,i===2?.4:.23,.08,0,0,.03,black,.025);for(let y=-.07;y<.09;y+=.04)box(p,.18,.012,.012,0,y,.075,chrome,.003);interactive(p,['Clutch','Brake','Accelerator'][i]);if(selected===['Clutch','Brake','Accelerator'][i])p.rotation.x=-.58;pedalObjects.push(p);}
 box(scene,.58,.42,1.8,.15,.3,.48,black,.12);const stick=new T.Group();scene.add(stick);cyl(stick,.032,.5,.15,.77,.38,chrome);mesh(new T.SphereGeometry(.13,24,16),black,stick,.15,1.04,.38);interactive(stick,'Gear lever');if(mode==='gear'&&selected!=='N'){stick.rotation.x=['1','3','5'].includes(selected)?-.14:.14;stick.rotation.z=['1','2'].includes(selected)?.11:['5','R'].includes(selected)?-.11:0;}label(scene,selected.match(/^[1-5R]$/)?selected:'N',.15,1.06,.505,.13,.09,'#172014','#d3fa69');const hand=box(scene,.1,.13,.55,.44,.61,.98,black);interactive(hand,'Handbrake');const mirror=box(scene,.72,.23,.08,0,2,-1.3,chrome);interactive(mirror,'Rear-view mirror');for(const side of [-1,1]){const mirror=box(scene,.42,.25,.1,side*2,1.5,-.75,chrome);interactive(mirror,'Side mirrors');}
 const indicator=box(scene,.42,.05,.06,1.46,1.22,-.04,black);interactive(indicator,'Indicators');interactive(scene.children.find(o=>o.position.x===0&&o.position.y===1.22)??stick,'Dashboard');const seat=box(scene,.7,.12,.8,.9,.5,1.2,black);const back=box(scene,.7,1.1,.14,.9,1,1.63,black);const belt=box(scene,.055,1,.035,.89,1,1.52,chrome);belt.rotation.z=.48;interactive(belt,'Seat belt');
 if(mode==='pedals'){baseCamera.set(1.5,1.3,3.1);target.set(.9,.35,-.1)}else if(mode==='gear'){baseCamera.set(1.7,2.2,2.8);target.set(.1,.7,.3)}else{baseCamera.set(.2,2.5,4.2);target.set(-.2,1,0)}
 }else{
 const roadIndex=scene.children.length;road();roadGroup=new T.Group();scene.children.slice(roadIndex).forEach(o=>roadGroup!.add(o));scene.add(roadGroup);vehicle=car(scene);vehicle.position.x=mode==='hero'?1.65:2.1;
 if(mode==='hero'){vehicle.rotation.y=-.22;for(const [x,z]of[[-2,1],[-2,-2.3],[4,-3.9],[4,3.9]])cone(x,z);cyl(scene,.045,2.6,-3,1.3,-4,chrome);box(scene,.8,.9,.06,-3,2.6,-4.04,white);label(scene,'L',-3,2.6,-3.995,.6,.7,'#f3f0de','#dd583f');baseCamera.set(8,3.8,10.5);target.set(.9,.55,.2);}
 else if(mode==='parking'){for(let z=-6;z<7;z+=3){box(scene,2,.025,.06,-2,-.035,z,white);box(scene,.06,.025,3,-3,-.035,z+1.5,white);}for(const z of [-4.5,4.5]){const other=car(scene,mat('#56636a',.65,.3));other.position.set(-1.9,0,z);other.scale.setScalar(.9)}for(const x of [-3.3,3.5])cone(x,6);const points=[];for(let i=0;i<=40;i++){const t=i/40;points.push(new T.Vector3(2-4*(t*t*(3-2*t)),-.015,4-4*t))}const curve=new T.CatmullRomCurve3(points);mesh(new T.TubeGeometry(curve,40,.035,6,false),lime);baseCamera.set(9,12,10);target.set(0,0,0);}
 else{city();cyl(scene,.045,2.2,-4.9,1.1,0,chrome);const stop=mesh(new T.CylinderGeometry(.45,.45,.07,8),mat('#c84838'),scene,-4.9,2.25,0);stop.rotation.x=Math.PI/2;label(scene,'STOP',-4.9,2.25,.045,.65,.25,'#c84838','#ffffff');const parked=car(scene,mat('#526672',.6,.35));parked.position.set(-2,0,-10);parked.rotation.y=Math.PI;parked.scale.multiplyScalar(.85);if(mode!=='highway'){traffic(-4,-4);traffic(4,4);for(let x=-4;x<4;x+=.8)box(scene,.5,.02,1.5,x,-.025,-4.9,white);box(scene,35,.14,7,0,-.17,-9,asphalt);for(let i=0;i<3;i++){cyl(scene,.13,.7,-5.2+i*.55,.45,-4.8,mat('#b1b897'));mesh(new T.SphereGeometry(.13,12,8),mat('#b1b897'),scene,-5.2+i*.55,.98,-4.8)}}else{for(const x of [-4.9,4.9]){box(scene,.1,.15,40,x,.65,0,chrome);for(let z=-18;z<20;z+=4)cyl(scene,.035,.75,x,.3,z,chrome)}}baseCamera.set(mode==='road'?9:7,mode==='road'?12:5.5,mode==='road'?12:11);target.set(0,0,-1);}
 }
 camera.position.copy(baseCamera);camera.lookAt(target);let width=0,height=0;function resize(){width=el!.clientWidth;height=el!.clientHeight;if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.zoom=Math.min(1,camera.aspect/(mode==='hero'?1.3:1.35));camera.updateProjectionMatrix();}resize();const ro=new ResizeObserver(resize);ro.observe(el);let visible=true;const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting});io.observe(el);let pointerX=0,pointerY=0;
 const ray=new T.Raycaster();const pointer=new T.Vector2();const move=(e:PointerEvent)=>{if(touch||reduced||!motionRef.current)return;const r=el!.getBoundingClientRect();pointerX=(e.clientX-r.left)/r.width-.5;pointerY=(e.clientY-r.top)/r.height-.5;};const click=(e:PointerEvent)=>{if(!picks.length)return;const r=el!.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(picks,false)[0];if(hit)callback.current?.(hit.object.userData.control)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',click);
 let frame=0,last=0,start=performance.now();function animate(now:number){frame=requestAnimationFrame(animate);if(!visible||document.hidden||now-last<(touch?33:22))return;last=now;const t=(now-start)/1000;camera.position.lerp(baseCamera.clone().add(new T.Vector3(pointerX*.3,pointerY*.12,0)),.045);camera.lookAt(target);if(roadGroup&&mode==='hero')roadGroup.scale.z=reduced?1:Math.min(1,.3+t*1.3);if(vehicle){const progress=live.current.progress;if(mode==='hero'){vehicle.position.y=reduced||!motionRef.current?0:Math.sin(t*1.3)*.006;vehicle.position.z=reduced?0:Math.max(0,1-t)*2;}else if(mode==='parking'){const a=live.current.playing&&!reduced?(Math.sin(t*.48-Math.PI/2)+1)/2:progress;const smooth=a*a*(3-2*a);if(selected==='Bay parking'){vehicle.position.set(2-4*smooth,0,3-3*a);vehicle.rotation.y=-Math.PI/2*smooth;}else if(selected==='Reverse parking'){vehicle.position.set(2-4*smooth,0,-3+3*a);vehicle.rotation.y=Math.PI/2*smooth;}else if(selected==='Turning exercise'){vehicle.position.set(Math.sin(a*Math.PI)*2,0,3*a);vehicle.rotation.y=a*Math.PI;}else{vehicle.position.set(2-4*smooth,0,4-4*a);vehicle.rotation.y=Math.sin(a*Math.PI)*.7;}}else{vehicle.position.z=T.MathUtils.lerp(vehicle.position.z,-6+progress*9,.055);if(mode==='road'){vehicle.position.x=2.1+Math.sin(vehicle.position.z*.12)*1.6;vehicle.rotation.y=Math.cos(vehicle.position.z*.12)*.19}else vehicle.rotation.y=0;}}if(wheel&&selected==='Steering wheel')wheel.rotation.z=.12;renderer.render(scene,camera)}frame=requestAnimationFrame(animate);setReady(true);
 const contextLost=(e:Event)=>{e.preventDefault();setError(true)};renderer.domElement.addEventListener('webglcontextlost',contextLost);
 cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',click);renderer.domElement.removeEventListener('webglcontextlost',contextLost);const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments){geometries.add(o.geometry);const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{materials.add(m);if(m.map)textures.add(m.map)})}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();renderer.dispose();renderer.domElement.remove();};
 }catch(e){cleanup();console.error('Driving scene could not load',e);if(!cancelled)setError(true)}} ,{rootMargin:'180px'});observer.observe(el);return()=>{cancelled=true;observer.disconnect();cleanup();};
 },[mode,selected,weather]);
 return <div ref={host} className={`driving-scene ${className}`} role="group" aria-label={`Interactive 3D ${mode==='hero'?'learner car on a practice road':mode+' learning environment'}`}>{ready&&!error&&mode==='hero'&&<button className="motion-toggle" onClick={()=>setMotion(!motion)} aria-pressed={!motion}>{motion?'Pause motion':'Resume motion'}</button>}{!ready&&!error&&<span className="scene-loading">PREPARING YOUR DRIVE</span>}{error&&<div className="error-note">3D view is unavailable on this device. All lessons and controls are available below.</div>}</div>;
}



export default function DrivingScene(props:SceneProps){const outer=useRef<HTMLDivElement>(null);const[near,setNear]=useState(false);useEffect(()=>{const el=outer.current;if(!el)return;const observer=new IntersectionObserver(entries=>setNear(entries[0].isIntersecting),{rootMargin:'250px'});observer.observe(el);return()=>observer.disconnect()},[]);return <div ref={outer} className="scene-lifecycle">{near?<SceneEngine {...props}/>:<div className="scene-rest" aria-label={props.mode?props.mode+' learning scene':'Learner car scene'}/>}</div>}

