"use client";
import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {Header,Footer,PageIntro} from './Shell';
import {Cockpit,Starting,Pedals,Gears,Parking,Environment,Guidance} from './Modules';
import DrivingScene from './DrivingScene';
import {milestones} from './content';
import {Check,ArrowRight,CheckCircle2} from 'lucide-react';
export default function Learn(){const[index,setIndex]=useState(0);const[complete,setComplete]=useState<number[]>([]);const[storageError,setStorageError]=useState(false);
useEffect(()=>{const p=Number(new URLSearchParams(location.search).get('lesson'));if(Number.isInteger(p)&&p>=0&&p<13)setIndex(p);try{const saved=JSON.parse(localStorage.getItem('tlz-progress')||'[]');if(Array.isArray(saved))setComplete(saved.filter((v:unknown)=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<13))}catch{setStorageError(true)}},[]);
useEffect(()=>{type Context={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'open_driving_lesson',title:'Open a driving lesson',description:'Open one of the 13 learning lessons. Does not mark it complete.',inputSchema:{type:'object',properties:{lesson:{type:'integer',minimum:1,maximum:13}},required:['lesson'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const value=input as {lesson?:unknown};if(!Number.isInteger(value?.lesson)||Number(value.lesson)<1||Number(value.lesson)>13)throw new Error('lesson must be an integer from 1 to 13');flushSync(()=>setIndex(Number(value.lesson)-1));return{lesson:value.lesson,title:milestones[Number(value.lesson)-1].title}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
function mark(){const next=complete.includes(index)?complete:[...complete,index];setComplete(next);try{localStorage.setItem('tlz-progress',JSON.stringify(next))}catch{setStorageError(true)}}
const m=milestones[index];return <><Header/><main><PageIntro kicker="THE LEARNING STUDIO" title="Confidence, one skill at a time." description="Explore the controls. Understand the habits. Take what you learn into your next supervised lesson."/><div className="learning-layout"><aside className="curriculum"><span className="small-label">YOUR LEARNING ROAD</span><div className="progress-track"><span style={{width:`${complete.length/13*100}%`}}/></div><p>{complete.length} of 13 lessons reviewed · {storageError?'Session only':'Saved on this device'}</p><nav aria-label="Lessons">{milestones.map((v,i)=><button key={v.title} aria-current={i===index?'step':undefined} onClick={()=>setIndex(i)}><span>{complete.includes(i)?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{v.title}<ArrowRight size={13}/></button>)}</nav></aside><div className="learning-content"><div className="lesson-topline"><span>LESSON {String(index+1).padStart(2,'0')}</span><span>{m.tag}</span></div>{index===0?<Cockpit/>:index===1?<Starting/>:index===2?<Pedals/>:index===3?<Gears/>:index===7||index===8?<Parking/>:index===10||index===12?<Environment/>:<div><div className="scene-panel lesson-scene"><DrivingScene mode={m.mode} progress={index/12}/></div><div className="lesson-panel"><div className="eyebrow">{m.tag}</div><h2>{m.title}</h2><p className="body-copy">{m.description}</p><ul className="tip-list">{m.tips.map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul>{index===11&&<a className="button lime" href="/test">Take the free practice test <ArrowRight size={16}/></a>}</div></div>}<div className="lesson-completion"><button className="button outline" onClick={mark}>{complete.includes(index)?<><CheckCircle2 size={18}/> Lesson reviewed</>:<>Mark as reviewed <Check size={18}/></>}</button><button className="button lime" disabled={index===12} onClick={()=>setIndex(index+1)}>Next lesson <ArrowRight size={18}/></button></div><p className="fine-print">Review progress tracks what you’ve read, not your readiness to drive independently.</p></div></div><Guidance/></main><Footer/></>}
