"use client";
import {useState} from 'react';
import {ArrowUpRight,Menu,X,ArrowLeft,MessageCircle} from 'lucide-react';
import {instagramUrl,whatsappUrl,whatsappDisplayNumber} from '@/lib/contact';
export function WhatsAppLink(){return <a className="social-link" href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label={`WhatsApp ${whatsappDisplayNumber} (opens in a new tab)`}><MessageCircle size={18} aria-hidden="true"/><span>WhatsApp · {whatsappDisplayNumber}</span><ArrowUpRight size={15} aria-hidden="true"/></a>}
export function InstagramLink(){return <a className="social-link" href={instagramUrl} target="_blank" rel="noopener noreferrer" aria-label="Visit @thelearnerzone on Instagram (opens in a new tab)"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg><span>@thelearnerzone</span><ArrowUpRight size={15} aria-hidden="true"/></a>}
export function Header(){const[open,setOpen]=useState(false);return <header className="header"><a className="brand" href="/" aria-label="The Learner Zone home"><span className="brandmark">L<span>↗</span></span><span>THE LEARNER<span className="brandzone">ZONE</span></span></a><nav className={open?'nav open':'nav'} aria-label="Main navigation"><a href="/#journey">The journey</a><a href="/learn">Learn to drive</a><a href="/signs">Road signs</a><a href="/test">Mock test <span className="free">FREE</span></a><a href="/#contact">Contact</a></nav><a className="navcta" href="/lessons">Book a lesson <ArrowUpRight size={17}/></a><button className="menu" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>}
export function Footer(){return <footer><a className="footer-name" href="/">THE LEARNER ZONE</a><p>Learn. Practice. Test. Drive.</p><a href="/learn#guidance">Learning guidance & sources</a><WhatsAppLink/><InstagramLink/><span>© {new Date().getFullYear()} The Learner Zone</span><a href="/credits/assets.txt" className="asset-credit">3D model credits</a></footer>}
export function PageIntro({kicker,title,description}:{kicker:string;title:string;description:string}){return <div className="page-intro"><a href="/" className="backlink"><ArrowLeft size={15}/> Back to the journey</a><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{description}</p></div>}
