"use client";
import {useState} from 'react';
import {Header,Footer,PageIntro} from './Shell';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Search,ArrowUpRight,Octagon,Triangle,ParkingSquare,ArrowUp,PersonStanding,TrafficCone,Minus,Undo2} from 'lucide-react';
import DrivingScene from './DrivingScene';
export const signs=[
{name:'Stop',category:'Mandatory',symbol:'STOP',shape:'stop',meaning:'Come to a complete stop where required. Observe the junction and proceed only when safe and permitted.'},
{name:'No entry',category:'Mandatory',symbol:'−',shape:'round',meaning:'Do not enter from this direction. Look for a permitted route.'},
{name:'Give way',category:'Mandatory',symbol:'▽',shape:'yield',meaning:'Give way to traffic on the road you are joining. Stop if needed to proceed safely.'},
{name:'No U-turn',category:'Mandatory',symbol:'↶',shape:'round',meaning:'A U-turn is not permitted here. Continue to a safe, legal turning opportunity.'},
{name:'Bend ahead',category:'Warning',symbol:'↱',shape:'triangle',meaning:'A bend is ahead. Assess the road and adjust your speed before reaching it.'},
{name:'Road works',category:'Warning',symbol:'⚒',shape:'triangle',meaning:'Road works are ahead. Watch for workers, temporary signs and changes to the road layout.'},
{name:'Pedestrian crossing',category:'Warning',symbol:'↟',shape:'triangle',meaning:'Watch for a pedestrian crossing ahead and be prepared to stop as local rules require.'},
{name:'Parking',category:'Informatory',symbol:'P',shape:'info',meaning:'Parking is indicated. Check nearby signs for time limits, restrictions and conditions.'},
{name:'Hospital',category:'Informatory',symbol:'H',shape:'info',meaning:'A hospital is nearby. Stay alert for entrances, pedestrians and emergency vehicles.'},
{name:'One-way road',category:'Informatory',symbol:'↑',shape:'info',meaning:'Traffic travels in the indicated direction. Follow the signs and choose your lane in good time.'},
{name:'Lane divider',category:'Road markings',symbol:'┆',shape:'marking',meaning:'Broken lines separate traffic lanes. Change lanes only when permitted and safe, after checking and signalling.'},
{name:'Stop line',category:'Road markings',symbol:'━',shape:'marking',meaning:'Indicates where to stop when required by a signal or sign. Keep behind the line.'},
{name:'Pedestrian crossing markings',category:'Road markings',symbol:'▥',shape:'marking',meaning:'A designated crossing area. Watch for pedestrians and follow applicable crossing rules.'}
];

function SignIcon({sign}:{sign:(typeof signs)[number]}){return <span className="road-sign-symbol" aria-hidden="true"><svg viewBox="0 0 100 100">{sign.shape==='stop'?<><polygon points="30,4 70,4 96,30 96,70 70,96 30,96 4,70 4,30" fill="#c94132" stroke="#fff" strokeWidth="4"/><text x="50" y="58" textAnchor="middle" fill="white" fontSize="25" fontWeight="800">STOP</text></>:sign.shape==='triangle'?<><path d="M50 7 L95 91 H5 Z" fill="#f9faee" stroke="#d54836" strokeWidth="7" strokeLinejoin="round"/>{sign.name==='Pedestrian crossing'?<g transform="translate(33,39) scale(1.5)" stroke="#162012"><PersonStanding size={24}/></g>:sign.name==='Road works'?<g transform="translate(34,45) scale(1.35)" stroke="#162012"><TrafficCone size={24}/></g>:<path d="M47 77 V57 Q47 45 65 43" fill="none" stroke="#162012" strokeWidth="8"/>}</>:sign.shape==='yield'?<path d="M7 10 H93 L50 91 Z" fill="#fffdec" stroke="#d54836" strokeWidth="7" strokeLinejoin="round"/>:sign.shape==='round'?<><circle cx="50" cy="50" r="44" fill={sign.name==='No entry'?'#d34837':'#fffdec'} stroke="#d34837" strokeWidth="7"/>{sign.name==='No entry'?<path d="M20 50 H80" stroke="white" strokeWidth="15"/>:<><path d="M64 72 V38 Q64 20 40 30 Q33 35 33 45 V60 M23 49 L33 61 L43 49" fill="none" stroke="#172011" strokeWidth="6"/><path d="M20 19 L81 81" stroke="#d34837" strokeWidth="7"/></>}</>:<><rect x="4" y="4" width="92" height="92" rx="3" fill={sign.shape==='info'?'#276da6':'#465640'} stroke="#eef5e7" strokeWidth="4"/><text x="50" y="71" fontSize="65" fill="white" textAnchor="middle" fontWeight="700">{sign.symbol}</text></>}</svg></span>}

export function Signal(){const[color,setColor]=useState('Red');return <div className="interactive-grid"><div className="scene-panel"><DrivingScene mode="city" selected={color} onSelect={setColor}/></div><div className="lesson-panel"><div className="eyebrow">READ THE ROAD</div><h3>A moment to observe.</h3><div className="signal-buttons">{['Red','Amber','Green'].map(c=><button key={c} className={color===c?'active':''} aria-pressed={color===c} onClick={()=>setColor(c)}><span style={{background:{Red:'#f26757',Amber:'#f7bd55',Green:'#badd71'}[c]}}/>{c}</button>)}</div><h4>{color==='Red'?'Stop.':color==='Amber'?'Read the situation.':'Go only when it’s safe.'}</h4><p className="body-copy">{color==='Red'?'Wait behind the stop line. Keep the crossing clear.':color==='Amber'?'Amber rules vary by location. In the UK, stop unless you have crossed the line or are too close to stop safely.':'Check that the way is clear and movement is permitted. Continue watching for pedestrians and turning vehicles.'}</p><a className="textlink" href="https://www.gov.uk/guidance/the-highway-code/light-signals-controlling-traffic" target="_blank" rel="noreferrer">UK signal reference <ArrowUpRight size={16}/></a></div></div>}
export default function Signs(){const[query,setQuery]=useState('');const[category,setCategory]=useState('All signs');const[selected,setSelected]=useState<(typeof signs)[number]|null>(null);const categories=['All signs','Mandatory','Warning','Informatory','Road markings','Traffic signals'];const filtered=signs.filter(s=>(category==='All signs'||s.category===category)&&`${s.name} ${s.meaning}`.toLowerCase().includes(query.toLowerCase()));return <><Header/><main><PageIntro kicker="THE LANGUAGE OF THE ROAD" title="See the sign. Know what’s next." description="Build recognition before you meet a sign on the road. Explore common examples and the decisions behind them."/><div className="sign-library"><p className="notice">Introductory examples. Sign designs, categories and legal meanings vary by country. Confirm with your local road authority.</p><div className="searchbox"><Search size={19}/><input aria-label="Search road signs" placeholder="Search signs, e.g. parking" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}>Clear</button>}</div><Tabs value={category} onValueChange={setCategory}><TabsList className="topic-tabs">{categories.map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList>{categories.map(c=><TabsContent value={c} key={c}>{c==='Traffic signals'?<Signal/>:<><p className="result-count" role="status">{filtered.length} {filtered.length===1?'sign':'signs'} to explore</p><div className="sign-grid">{filtered.map(s=><button className="sign-card" key={s.name} onClick={()=>setSelected(s)}><SignIcon sign={s}/><span className="small-label">{s.category}</span><h3>{s.name}</h3><span className="textlink">Explore meaning <ArrowUpRight size={16}/></span></button>)}</div>{!filtered.length&&<div className="empty-state"><h3>No matching signs</h3><p>Try a different term, or explore all categories.</p><button className="button outline" onClick={()=>{setQuery('');setCategory('All signs')}}>Show all signs</button></div>}</>}</TabsContent>)}</Tabs></div><Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="sign-dialog">{selected&&<><SignIcon sign={selected}/><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.meaning}</DialogDescription><p className="fine-print">Check the design and rule used in your location.</p></>}</DialogContent></Dialog></main><Footer/></>}

